name: sample
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  font_awesome_flutter: ^8.7.0
  shared_preferences: ^0.5.6+2
  package_info: ^0.4.0+14
  sprintf: ^4.0.2
  fluttertoast: ^3.1.3
  flutter_staggered_grid_view: ^0.3.0
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.3.0
  firebase_analytics: ^5.0.11
  firebase_core: ^0.4.4+2
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
